Support for optional handler name
projectriff/java-function-invoker pull request #106
Opened 2018-11-12 14:19 UTC by dsyer

If there is a single function the handler=... from the
function.uri can be dropped

2018-11-12 14:28 UTC, dsyer commented
Build is green for me locally. I'll see if I can work out what is different.

2018-11-12 21:28 UTC, trisberg requested changes
Looks good other than an issue when passing in `handler=` which  results in an NPE

```
Caused by: java.lang.NullPointerException
	at org.springframework.cloud.function.deployer.FunctionCreatorConfiguration$BeanCreator.getFunctionNames(FunctionCreatorConfiguration.java:392)
	at org.springframework.cloud.function.deployer.FunctionCreatorConfiguration.functionNames(FunctionCreatorConfiguration.java:138)
	at org.springframework.cloud.function.deployer.FunctionCreatorConfiguration.init(FunctionCreatorConfiguration.java:119)
	... 24 more
```
Unfortunately this is what the buildpack does currently, see https://github.com/projectriff/riff-buildpack/issues/18

I would suggest guarding against this and maybe logging a warning message.

2018-11-13 08:37 UTC, dsyer commented
Fixed, thanks.

2018-11-13 15:45 UTC, trisberg approved these changes

2018-11-13 15:46 UTC, merged